export const DEFAULT_CURRENCY = "EUR";
export const DEFAULT_LOCALE = "fr-FR";
export const DEFAULT_TIMEZONE = "Europe/Paris";
export const MONTHLY_SUMMARY_WINDOW = 12;
export const POWENS_PROVIDER_ID = "powens";

export const DEFAULT_FIREBASE_PUBLIC_CONFIG = {
  EXPO_PUBLIC_FIREBASE_API_KEY: "AIzaSyAhdwrCfYyYNhJIwEpxOqoeQeTm0I5k_pc",
  EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN: "bankllink.firebaseapp.com",
  EXPO_PUBLIC_FIREBASE_PROJECT_ID: "bankllink",
  EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET: "bankllink.firebasestorage.app",
  EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "915210189378",
  EXPO_PUBLIC_FIREBASE_APP_ID: "1:915210189378:web:960bcafa5aada3ebdf8bdb",
  EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID: "G-PVM4YSYGBS"
} as const;
